/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuuzed_androidx_serialport_NativeSerialPort */

#ifndef _Included_com_tuuzed_androidx_serialport_NativeSerialPort
#define _Included_com_tuuzed_androidx_serialport_NativeSerialPort
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_tuuzed_androidx_serialport_NativeSerialPort
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL
Java_com_tuuzed_androidx_serialport_NativeSerialPort_nativeOpen(
        JNIEnv *env, jclass type, jstring path,
        jint baudRate, jint dataBit, jint stopBit,
        jint parity
);


/*
 * Class:     com_tuuzed_androidx_serialport_NativeSerialPort
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_tuuzed_androidx_serialport_NativeSerialPort_nativeClose(
        JNIEnv *env, jobject instance
);


#ifdef __cplusplus
}
#endif
#endif
